proxy:
  resources:
    cpu:
      request: 50m
      limit: 500m
    memory:
      request: 32Mi
      limit: 256Mi
proxyInit:
  resources:
    cpu:
      request: 10m
      limit: 100m
    memory:
      request: 10Mi
      limit: 64Mi
policyController:
  resources:
    cpu:
      request: 50m
      limit: 500m
    memory:
      request: 32Mi
      limit: 256Mi
destinationResources: &id001
  cpu:
    request: 50m
    limit: 500m
  memory:
    request: 32Mi
    limit: 256Mi
identityResources: *id001
proxyInjectorResources: *id001
spValidatorResources: *id001
heartbeatResources: *id001
